{% set version = "0.4.16" %}

package:
  name: pyafv
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyafv/pyafv-{{ version }}.tar.gz
  sha256: aa1d26b2042aa80aec6134852af9cb240210615e2f52bd4ab0000486e6eb2c65

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=1.26.4                         # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    # remove: - python-gil
    - hatchling
    - hatch-cython
    - cython
    - setuptools
    - numpy >=1.26.4
    - pip
  run:
    - python
    # remove: - python-gil
    - numpy >=1.26.4
    - scipy >=1.13.1
    - matplotlib-base >=3.8.4

test:
  imports:
    - pyafv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyafv.github.io
  summary: 'Python implementation of the active finite Voronoi (AFV) model.'
  description: |
    PyAFV is a Python library for simulating cellular tissues using
    active finite Voronoi (AFV) model. It provides tools for studying
    collective cell behavior such as motility, adhesion, jamming, and
    tissue fracture in active matter and biophysical systems.
  doc_url: https://pyafv.readthedocs.io
  dev_url: https://github.com/wwang721/pyafv
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wwang721
